# This configuration uses ini-style syntax. Lines beginning with # are comments.
; ; can be used too!

# This first section of the file is called the "global" section, any settings
# declared here will be used in all 3 M "profiles".

# This binds the G1 key to the x key. Pushing down on the G1 key will be
# equivalent to pushing down the x key on your keyboard. Releasing it will
# release the x key.
# This happens in all 3 m profiles
G1=x

# This does the same, but also presses all modifiers along with the x key.
G2=Ctrl+Alt+Shift+Super+x

# Pressing multiple keys is currently not possible, so this will not work
; G3=x+y

# up, down, left, and right refer to the keybinds that are bound to the
# joystick. Here, we say we want to bind the WASD keys to the 4 directions of
# the joystick in all 3 M modes.
up=w
down=s
left=a
right=d

# Thumb left and thumb right refer to the keys to the left and right of the
# joystick. Thumb stick refers to pushing the thumbstick down.
thumb left=mouse1
thumb right=mouse2
thumb stick=space

# Here is a list of all the valid modifiers:
#
# shift, lshift, rshift, alt, lalt, ralt, altgr, ctrl, lctrl, rctlr, super,
# lsuper, rsuper
#
# The valid mouse buttons:
#
# mouse1 mouse2 mouse3 mouse4 mouse5
#
# Their alternative names:
#
# mouse left mouse middle mouse right mouse extra mouse side
#
# And a list of all the keys:
#
# ~ 1 2 3 4 5 6 7 8 9 0 - =
# q w e r t y u i o p [ ] \
# a s d f gh j k l ; '
# z x c v b n m , . /
# f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12
# esc enter backspace tab capslock space

# Providing a path to a script here will load the provided script. Currently,
# only Lua scripts are supported.
script = example_config.lua

# Instead of encoding the path, using the value "lua" will replace the "ini"
# extension in the name of the current file with lua and load that file as a
# script.
; script = lua

# [M1], [M2], and [M3] start a profile section. Anything in that block only
# applies to that section.
[M1]
# We can give each block its own color by providing it as a hex color code
#
# This can also be done in the global section if you just want one color for
# all 3 profiles.
color=#FE218B

# This keybind is only bound when in M1 mode.
G4=Shift+1

# Override the previously defined binding for G1 in M1 mode.
G1=O

# Script can only occur in the global section.
; script = lua

[M2]
color=#FED700

[M3]
color=#21B0FE
