name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  FEATURES: handler_static,handler_lua55,mlua/vendored

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: format
      run: cargo fmt --check

    - name: Install libudev
      run: |
        sudo apt update
        sudo apt install libudev-dev

    - name: Cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: check
      run: cargo check --bins --features bin,${{ env.FEATURES }}

    - name: clippy
      run: cargo clippy --bins --features bin,${{ env.FEATURES }}

    - name: docs
      run: cargo clippy --features ${{ env.FEATURES }}
